### ISSUE TITLE
Dumps out without deleting even when older records exist

### ISSUE THREAD

**Issue by ssx** [jmathai/amnesia#2]
I can ping you over a set of tokens if you want to toy with the account too.

<img width="738" alt="screen shot 2016-11-30 at 09 49 16" src="https://cloud.githubusercontent.com/assets/254889/20745624/7e0e5916-b6e2-11e6-8c89-05925cb55648.png">

**Comment by jmathai** [comment]
Do you mind emailing me the tokens? My account only has a few tweets because I run this regularly. Would like to try and reproduce on an account with more tweets.

**Comment by ssx** [comment]
Yep, which address?

**Comment by jmathai** [comment]
jaisen at github username dot com

**Comment by ssx** [comment]
sent!
